# Copyright 2023 XigXog
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ componentFullName }}
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- range $k, $v := .Values.serviceLabels }}
    {{- printf "%s: %s" $k ($v | cleanLabel | quote) | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
    {{- with .Values.serviceAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  selector:
    {{- include "selectors" . | nindent 4 }}
  ports:
    - name: http
      port:  {{ .Values.httpPort | default 80 }}
      targetPort: http
      protocol: TCP
    - name: https
      port:  {{ .Values.httpsPort | default 443 }}
      targetPort: https
      protocol: TCP
