# Copyright 2023 XigXog
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ name }}-operator
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
webhooks:
  - name: index-mutation.kubefox.xigxog.io
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ name }}-operator
        namespace: {{ namespace }}
        path: /index/mutate
    rules:
      - apiGroups:
          - kubefox.xigxog.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - appdeployments
          - datasnapshots
          - environments
          - virtualenvironments

  - name: platform-mutation.kubefox.xigxog.io
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ name }}-operator
        namespace: {{ namespace }}
        path: /v1alpha1/platforms/mutate
    rules:
      - apiGroups:
          - kubefox.xigxog.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - platforms

  - name: snapshot-mutation.kubefox.xigxog.io
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ name }}-operator
        namespace: {{ namespace }}
        path: /v1alpha1/datasnapshots/mutate
    rules:
      - apiGroups:
          - kubefox.xigxog.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - datasnapshots

  - name: secrets-mutation.kubefox.xigxog.io
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ name }}-operator
        namespace: {{ namespace }}
        path: /secrets/mutate
    rules:
      - apiGroups:
          - kubefox.xigxog.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - datasnapshots
          - environments
          - virtualenvironments