name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v1
